name: Bug Report
description: Is something not working as expected? Submit a bug.
title: "[BUG] REPLACE WITH A SHORT DESCRIPTION"
labels: [bug, needs-triage]
assignees:
  - 
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a [Code of Conduct](https://github.com/vmware/terraform-provider-nsxt/blob/master/CODE_OF_CONDUCT.md) that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
  - type: input
    id: version-terraform-provider-nsxt
    attributes:
      label: Terraform Provider
      description: Please provide the Terraform provider for NSX-T Data Center version.
      placeholder: e.g. v3.2.5
  - type: input
    id: version-nsx
    attributes:
      label: VMware NSX-T Data Center
      description: Please provide the VMware NSX-T Data Center version.
      placeholder: e.g. v3.1.3
    validations:
      required: true
  - type: input
    id: version-terraform
    attributes:
      label: Terraform
      description: Please provide the Terraform version.
      placeholder: e.g. 1.0.10
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please add any information you can provide about the environment.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue you are experiencing.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        What is it you expected to happen?
        This should be a description of how the functionality you tried to use is supposed to work.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened that's different from the expected behavior?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log Fragments and Files
      description:  |
        Please include appropriate log fragments. If the log is longer than a few dozen lines, please include the URL to the [Gist](https://gist.github.com/) of the log or use the [GitHub detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Screenshots of the issue, if applicable.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide a code repository, gist, code snippet, sample files, screenshots, or anything else you think will aid in reproducing the issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Community Note
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
