name: golangci-ut
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          go get .
          go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./nsxt/metadata/...
