name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
            go-version: 1.14

      -
        uses: actions/checkout@v2

      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
          args: --issues-exit-code=1
          only-new-issues: true
